greenbone/workflows

- .github/workflows/helm-build-push.yml
- .github/workflows/release-3rd-gen.yml
- .github/workflows/release-cloud.yml
Add: Release workflows for Cloud and 3rd Gen, Helm build-push
Add generic workflows to call from different repos
DEVOPS-672
> Add: Release workflows for Cloud and 3rd Gen, Helm build-push

- .github/workflows/ci-python.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/release-python.yml
Add reusable workflows for our public python repos
Allow to use generic workflows for our public python repos.
> Add: Add reusable workflows for our public python repos

- .github/workflows/helm-build-push.yml
- .github/workflows/release-3rd-gen.yml
- .github/workflows/release-cloud.yml
- .github/workflows/release-generic.yml
- README.md
Fix issues in release and helm chart workflows
The workflows are broken currently.
> Fix issues in release and helm chart workflows

- .github/workflows/check-version.yml
Use check-version action for check-version workflow
Surprisingly I did wrote an action for checking the versioning.
> Change: Use check-version action for check-version workflow

- .github/workflows/container-build-push-3rd-gen.yml
Add: Workflow container-build-push for 3rd gen
DEVOPS-719
DEVOPS-719
> Add: Workflow container-build-push for 3rd gen

- .github/workflows/release-generic.yml
Add:  release-generic.yml update-project input value
Needed in some releases like https://github.com/greenbone/opensight-keycloak
DEVOPS-718
> Add:  release-generic.yml update-project input value

- .github/workflows/release-3rd-gen.yml
Add: release-3rd-gen.yml update-project input value
Needed in some releases like https://github.com/greenbone/opensight-keycloak
DEVOPS-718
> Add: release-3rd-gen.yml update-project input value

- .github/workflows/container-build-push-3rd-gen.yml
- .github/workflows/container-build-push-docker.yml
- .github/workflows/container-build-push-generic.yml
- .github/workflows/container-build-push-ghcr.yml
- README.md
Add: `build-args` input to docker-build-push workflow(s)
Required for some build processes
./.
> Add: `build-args` input to docker-build-push workflow(s)

- .github/workflows/release-cloud.yml
- .github/workflows/release-generic.yml
Add: git-tag-prefix for cloud release
working cloud releases
DEVOPS-733
> Add: git-tag-prefix for cloud release

- .github/workflows/codecov-python.yml
- .github/workflows/docs-python.yml
- .github/workflows/lint-python.yml
- .github/workflows/test-python.yml
- .github/workflows/typing-python.yml
Remove `cache: "true"` input
Workflow currently fails ...
> Fix: Remove `cache: "true"` input

- .github/workflows/notify-mattermost-feed-deployment.yml
Add: notify mattermost feed deployment workflow
DEVOPS-722
DEVOPS-722
> Add: notify mattermost feed deployment workflow

- .github/workflows/helm-container-build-push-3rd-gen.yml
- .github/workflows/notify-mattermost-3rd-gen.yml
- .github/workflows/release-3rd-gen.yml
Add: notify-mattermost-3rd-gen.yml
DOS-84
DOS-84
> Add: notify-mattermost-3rd-gen.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
Fix: if statement in helm-container-build-push-3rd-gen.yml
The action if statement seems to have a syntax error.
None
> Fix: if statement in helm-container-build-push-3rd-gen.yml

- README.md
Add: update README.md for notify mattermost workflows
DEVOPS-722
DOS-84
DEVOPS-722
DOS-84
> Add: update README.md for notify mattermost workflows

- .github/workflows/notify-mattermost-3rd-gen.yml
Change: notify to  PD:3rdGenDeployment channel
We need to notify in this channel.
DOS-84
DOS-84
> Change: notify to  PD:3rdGenDeployment channel

- .github/workflows/helm-build-push-3rd-gen.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: secrets in  helm-build-push-3rd-gen.yml
Change: secrets in helm-container-build-push-3rd-gen.yml
Dependabot don't have this secrets and on PR's this secrets are not needed.
None
> Change: secrets in  helm-build-push-3rd-gen.yml

- .github/workflows/notify-mattermost-3rd-gen.yml
- .github/workflows/notify-mattermost-feed-deployment.yml
Fix: mattermost notify if statement
None
> Fix: mattermost notify if statement

- .github/workflows/notify-mattermost-3rd-gen-ci.yml
Add: notify-mattermost-3rd-gen-ci.yml workflow
3rd gen CI notify.
DOS-84
> Add: notify-mattermost-3rd-gen-ci.yml workflow

- .github/workflows/notify-mattermost-feed-deployment.yml
Change: use MATTERMOST_WEBHOOK_URL in  notify-mattermost-feed-deployment.yml
None
None
> Change: use MATTERMOST_WEBHOOK_URL in  notify-mattermost-feed-deployment.yml

- .github/workflows/notify-mattermost-feed-deployment.yml
Fix: secrets in notify-mattermost-feed-deployment.yml
Wrong input secrets.
None
> Fix: secrets in notify-mattermost-feed-deployment.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
- README.md
Add: inputs value to use greenbonebot as registry login
Sometimes we need the permissions from greenbonebot, to build a new docker image.
None
> Add: inputs value to use greenbonebot as registry login

- .github/workflows/auto-merge.yml
Activate auto-merge on open PRs
Save clicks on the web UI
DEVOPS-804
> Add: Workflow to activate auto-merge on a PR

- .github/workflows/helm-build-push-3rd-gen.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: support for init container tag update
DEVOPS-774
DEVOPS-774
> Add: support for init container tag update

- .github/workflows/helm-build-push-3rd-gen.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: image digest for init container
DEVOPS-774
DEVOPS-774
> Add: image digest for init container

- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: output container digest
None
none
> Add: output container digest

- README.md
Change: update README.md for 3rd gen helm and container build workflow
Need to be.
None
> Change: update README.md for 3rd gen helm and container build workflow

- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: enable greenbonebot token as build arg helm-container-build-push-3rd-gen.yml
We need it in some workflows.
None
> Change: enable greenbonebot token as build arg

- .github/workflows/helm-container-build-push-3rd-gen.yml
- README.md
Add: support for build-secrets in helm-container-build-push-3rd-gen.yml
In some workflows we need build secrets.
DEVOPS-821
> Add: support for build-secrets in helm-container-build-push-3rd-gen.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
- README.md
Change: Prohibit setting the greenbonebot token as build arg
DEVOPS-824
DEVOPS-824
> Change: Prohibit setting the greenbonebot token as build arg

- .github/workflows/container-build-push-3rd-gen.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
- README.md
Add: docker scout support into container related workflows
DEVOPS-830
DEVOPS-830
> Add: docker scout support into container related workflows

- .github/workflows/helm-container-build-push-3rd-gen.yml
Fix: scout empty string
We have to set an empty string otherwise the contains function set False as string
None
> Fix: scout empty string

- .github/workflows/notify-mattermost-3rd-gen.yml
Add: status check into notify-mattermost-3rd-gen.yml
Fix some fails in the release workflow notification.
None
> Add: status check into notify-mattermost-3rd-gen.yml

- .github/workflows/auto-merge.yml
Add: Input value to select merge mode and skip draft prs
DEVOPS-813
DEVOPS-813
> Add: Input value to select merge mode and skip draft prs

- .github/workflows/helm-build-push-3rd-gen.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: workflows to run in product helm chart repo
All service charts are moved to the product repository.
DEVOPS-905
> Change: workflows to run in product helm chart repo

- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: trigger for product helm chart upgrade
DEVOPS-863
DEVOPS-863
> Add: trigger for product helm chart upgrade

- .github/workflows/helm-container-build-push-3rd-gen.yml
Fix: helm-container-build-push-3rd-gen.yml
> Fix: helm-container-build-push-3rd-gen.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: use container-build-push-generic action
DEVOPS-884
DEVOPS-884
> Change: use container-build-push-generic action

- .github/workflows/helm-container-build-push-3rd-gen.yml
Add build for arm64
Required for apple silicon cpus
> Add build for arm64

- .github/workflows/helm-container-build-push-3rd-gen.yml
Reverts greenbone/workflows#82
> Revert "Add build for arm64"

- .github/workflows/container-build-push-2rd-gen.yml
Add: sensor-build-push.yml
Shared workflow for all sensor related containers.
DEVOPS-1073
> Add: docker-build-push for 2rd gen

- .github/workflows/container-build-push-2rd-gen.yml
Change: run arm build on native arm runner
DEVOPS-1080
DEVOPS-1080
> Change: run arm build on native arm runner

- .github/workflows/container-build-push-2nd-gen.yml
Add: artifact downloader into container-build-push-2nd-gen.yml
DEVOPS-1073
DEVOPS-1073
> Add: artifact downloader into container-build-push-2nd-gen.yml

- .github/workflows/container-build-push-2nd-gen.yml
Change: cosign over manifest
This should allow us to use the manifest list checksum to verify multi arch images.
DEVOPS-1082
> Change: cosign over manifest

- .github/workflows/release-3rd-gen.yml
3rdGen Release workflow make notification optional
To skip notify if not required
> Change: 3rdGen Release workflow make notification optional

- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: compose update into helm-container-build-push-3rd-gen.yml #93 
Lets upgrade our new compose setup to gather with the helm setup.
DEVOPS-1140
> Add: compose update into helm-container-build-push-3rd-gen.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: pass container digest to compose upgrade
We need he container digest later on for cosign.
None
> Add: pass container digest to compose upgrade

- .github/workflows/container-build-push-2nd-gen.yml
> Fix: Failing CI workflow for openvas-scanner

- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-feed.yml
> Change: remove ref and depth 0 from checkout

- .github/workflows/container-build-push-2nd-gen.yml
Fix: container-build-push-2nd-gen.yml
Fix fetch tags
None
> Fix: container-build-push-2nd-gen.yml

- .github/workflows/container-build-push-2nd-gen.yml
force fetch git tags
Avoid the `(would clobber existing tag)` failure
> Fix: force fetch git tags

- .github/workflows/container-build-push-2nd-gen.yml
https://github.com/docker/metadata-action?tab=readme-ov-file#typesemver
Tag could not be parsed via workflow dispatch ...
> Fix: Tags on workflow_dispatch event

- .github/workflows/container-build-push-feed.yml
Test pulling the image, so we can already see Manifest problems ...
Manifest seems to be
> Add: Test-pull the image

- .github/workflows/container-build-push-2nd-gen.yml
Remove: tag needs to start with v as this is never the case for feed images
> Remove: tag needs to start with v as this is never the case for feed images

- .github/workflows/helm-container-build-push-3rd-gen.yml
fix upload
[DEVOPS-1175](https://jira.greenbone.net/browse/DEVOPS-1175)
[DEVOPS-1175](https://jira.greenbone.net/browse/DEVOPS-1175)
> Fix: upload

- .github/workflows/container-build-push-2nd-gen.yml
Fix: is-latest-tag in container-build-push-2nd-gen.yml
Fix: is-latest-tag in container-build-push-2nd-gen.yml
None
> Fix: is-latest-tag in container-build-push-2nd-gen.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: pass image url to compose update
DEVOPS-1236
DEVOPS-1236
> Change: pass image url to compose update

- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: Enable greenbone reg upload
DEVOPS-1175
DEVOPS-1175
> Change: Enable greenbone reg upload

- .github/workflows/container-build-push-2nd-gen.yml
Fix: Tagging mess
the previous tagging lead to some unexpected behaviors and wrong image tagging
DEVOPS-1229
> Fix: Tagging mess

- .github/workflows/container-build-push-2nd-gen.yml
Fix: tagging one more time
fix #121 
DEVOPS-1229
> Fix: tagging one more time

- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: management-console support 
DEVOPS-1257
DEVOPS-1276
DEVOPS-1257
DEVOPS-1276
> Add: management-console support

- .github/workflows/container-build-push-3rd-gen.yml
Fix: job needs in  container-build-push-3rd-gen.yml
None
> Fix: job needs in  container-build-push-3rd-gen.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
Remove Helm related jobs.
deprecated
DEVOPS-1255
> Remove: Helm-Chart build&deploy

- .github/workflows/notify-mattermost-cloud-dependapot-pr.yml
Remove mandatory fields in notify-mattermost-cloud-dependapot-pr.yml
> Remove mandatory fields in notify-mattermost-cloud-dependapot-pr.yml

- .github/workflows/notify-mattermost-cloud-dependapot-pr.yml
Fix typo error in fetch_prs section
> Fix typo error in fetch_prs section

- .github/workflows/notify-mattermost-cloud-dependapot-pr.yml
Fix multiline output values in notify-mattermost-cloud-dependapot-pr.yml
> Fix multiline output values in notify-mattermost-cloud-dependapot-pr.yml

- .github/workflows/notify-mattermost-cloud-dependapot-pr.yml
Update title with bold in notify-mattermost-cloud-dependapot-pr.yml
> Update title with bold in notify-mattermost-cloud-dependapot-pr.yml

- .github/workflows/notify-mattermost-cloud-dependapot-pr.yml
Fix the days parameter in notify-mattermost-cloud-dependapot-pr.yml
> Fix the days parameter in notify-mattermost-cloud-dependapot-pr.yml

- .github/workflows/container-build-push-3rd-gen.yml
Change: to greenbone reg
Use image url and digest from greenbone reg.
None
> Change: to greenbone reg

- .github/workflows/container-build-push-3rd-gen.yml
Fix: step id in container-build-push-3rd-gen.yml
> Fix: step id in container-build-push-3rd-gen.yml

- .github/workflows/check-version.yml
- .github/workflows/codecov-python.yml
- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-3rd-gen.yml
- .github/workflows/container-build-push-feed.yml
- .github/workflows/conventional-commits.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/docs-python.yml
- .github/workflows/lint-python.yml
- .github/workflows/notify-mattermost-2nd-gen.yml
- .github/workflows/notify-mattermost-3rd-gen-ci.yml
- .github/workflows/notify-mattermost-3rd-gen.yml
- .github/workflows/notify-mattermost-feed-deployment.yml
- .github/workflows/notify-mattermost-qm.yml
- .github/workflows/release-generic.yml
- .github/workflows/release-python.yml
- .github/workflows/test-python.yml
- .github/workflows/typing-python.yml
Changed the vX notation for actions to the actual hashcode.
The actions become immutable this way. Dependabot can update the hashcode to the last released version on it's own.
DEVOPS-1311
> Change: Versions to the hashcode

- .github/workflows/container-build-push-feed.yml
Remove tarball from Docker image
Docker image is not required to have the tarball included!
[#14589](https://github.com/greenbone/vulnerability-tests/pull/14589)
DEVOPS-1320
> Fix: Remove tarball from vts-image build process

- .github/workflows/container-build-push-2nd-gen.yml
Change: update container-multi-arch-manifest@f0c8b8268b98d09237774489fefc2c0ab77703aa # v3.27.13
Need to get the digest output
None
> Change: update container-multi-arch-manifest@f0c8b8268b98d09237774489fefc2c0ab77703aa # v3.27.13

- .github/workflows/container-build-push-2nd-gen.yml
Add: missing id field to create multi arch manifest
We need to redirect the manifest digest to the compose upgrade process.
None
> Add: missing id field to create multi arch manifest

- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-3rd-gen.yml
- .github/workflows/container-build-push-feed.yml
Add: harbor-replication to container-build-push-2nd-gen, container-build-push-3rd-gen, container-build-push-feed.yml
DOS-312
DOS-312
> Add: harbor-replication

- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-3rd-gen.yml
- .github/workflows/container-build-push-feed.yml
Change: use GREENBONE_REGISTRY_REPLICATION_TOKEN in container-build-push-2nd-gen.yml
Change: use GREENBONE_REGISTRY_REPLICATION_TOKEN in container-build-push-3rd-gen.yml
Change: use GREENBONE_REGISTRY_REPLICATION_TOKEN in container-build-push-feed.yml
DOS-312
DOS-312
> Change: use GREENBONE_REGISTRY_REPLICATION_TOKEN 

- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-3rd-gen.yml
- .github/workflows/container-build-push-feed.yml
Change: Check secret in bash
Github does not allow step if statements with secrets context.
None
> Change: Check secret in bash

- .github/workflows/codecov-python.yml
- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-3rd-gen.yml
- .github/workflows/container-build-push-feed.yml
- .github/workflows/conventional-commits.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/docs-python.yml
- .github/workflows/lint-python.yml
- .github/workflows/notify-mattermost-2nd-gen.yml
- .github/workflows/notify-mattermost-3rd-gen-ci.yml
- .github/workflows/notify-mattermost-3rd-gen.yml
- .github/workflows/notify-mattermost-cloud-dependapot-pr.yml
- .github/workflows/notify-mattermost-qm.yml
- .github/workflows/release-generic.yml
- .github/workflows/release-python.yml
- .github/workflows/test-python.yml
- .github/workflows/typing-python.yml
Unpin greenbone actions (we trust them)
We trust our own actions and take the risk of failing updates in favor of automatic updates ...
> Fix: Unpin greenbone actions (we trust them)

- .github/workflows/container-build-push-2nd-gen.yml
Fix line by removing double quote
The workflow syntax is wrong.
> Fix line by removing double quote

- .github/workflows/container-build-push-2nd-gen.yml
Fix: else typo in container-build-push-2nd-gen.yml
There was a typo in an if statement in container-build-push-2nd-gen.yml
None
> Fix: else typo in container-build-push-2nd-gen.yml

- .github/workflows/container-build-push-3rd-gen.yml
Change: Every service release container into dev project
DEVOPS-1342
DEVOPS-1342
> Change: Every service release container into dev project

- .github/workflows/container-push.yml
A universal workflow to build an multi arch image on arch native self-hosted runner.
Currently only amd64 and arm64
DEVOPS-1389
https://github.com/greenbone/pipeline-experiments/actions/runs/14930680844/job/41945880058
> Add: init container push

- .github/workflows/container-push.yml
Add: container digest output to container-push.yml
DEVOPS-1389
DEVOPS-1389
> Add: container digest output to container-push.yml

- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-3rd-gen.yml
Fix: Harbor returns always HTTP-Statuscode 200 OK
Harbor returns always HTTP-Statuscode 200 OK
We need to check the output!
None
> Fix: Harbor returns always HTTP-Statuscode 200 OK

- .github/workflows/container-build-push-feed.yml
Remove vulnerability-test.tar.xz in arm container
We dont need in the tar.xz inside the container
https://jira.greenbone.net/browse/DEVOPS-1431
> Fix: Remove vulnerability-test.tar.xz in arm container

- .github/workflows/generate-and-push-sbom-with-trivy-3rd-gen.yml
- Add type field for `output-file-name`
It was missing originally.
T5-1437
- [N/A] Tests
> Fix: Add missing type for input parameter

- .github/workflows/release-3rd-gen-generic.yml
- .github/workflows/release-3rd-gen.yml
- .github/workflows/release-agents.yml
- .github/workflows/release-generic.yml
Add: hotfix release in release-3rd-gen.yml
DEVOPS-1590
DEVOPS-1590
> Add: hotfix support

- .github/workflows/container-build-push-gea.yml
Improve input description for gea build push workflow
The descriptions were misleading.
> Improve input description for gea buils push workflow

- .github/workflows/container-build-push-gea.yml
More flexible container tags selection
Allow for more flexible container tags selections without having to override the tags input. At the end it should be possible to use this workflow to build gvm-libs container images easily.
> More flexible container tags selection

- .github/workflows/container-build-push-2nd-gen.yml
Change: trigger automatix update only on release in container-build-push-2nd-gen.yml
> Change: trigger automatix update only on release in container-build-push-2nd-gen.yml
