- .github/workflows/ci-python.yml
- .github/workflows/codecov-python.yml
Update python workflows
Extract codecov workflow. Codecov is unreliable and should not be run in a matrix. Therefore allow to include and run it separately.
Drop matrix from ci-python workflow. This allows to specify the matrix in the calling workflow.
Add mypy to ci-python workflow. Allow to run mypy via the ci-python workflow.
> Change: Update python workflows

- .github/workflows/ci-python.yml
- .github/workflows/codecov-python.yml
- README.md
Adjust running mypy in ci-python workflow
Allow to pass additional arguments to the mypy type checking job. By default this should not be necessary and all mypy settings should be included in the pyproject.toml file.
Requires https://github.com/greenbone/actions/pull/627
> Change: Adjust running mypy in ci-python workflow

- .github/workflows/ci-python.yml
- .github/workflows/lint-python.yml
- README.md
Allow to set linter for corresponding Python workflows
This will allow to use ruff in conjunction with our CI workflows.
> Allow to set linter for corresponding Python workflows

- .github/workflows/release-3rd-gen.yml
- .github/workflows/release-cloud.yml
- .github/workflows/release-python.yml
Extend `git-tag-prefix` input to all release workflows
will make `pontos` default to `""`
DEVOPS-733
> Add: Extend `git-tag-prefix` input to all release workflows

- .github/workflows/helm-build-push-3rd-gen.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
- README.md
Add: helm-container-build-push-3rd-gen and helm-build-push-3rd-gen
In order to have a reasonable container digest transfer to the helm chart release  we have to build the container and helm charts in the same workflow.
DEVOPS-773
> Add: helm-container-build-push-3rd-gen and helm-build-push-3rd-gen

- .github/workflows/notify-mattermost-feed-deployment.yml
Add: status input value  to notify-mattermost-feed-deployment.yml
Add: exit-with-status input value
It looks like if a job runs after an other job. And the first job fails but the second job runs always  e.g with "if: always()". The workflow run at the end is not in a fail state. So we need to fail this notify job by input value from the first job,
DEVOPS-722
> Add: status input value  to notify-mattermost-feed-deployment.yml

- .github/workflows/notify-mattermost-feed-deployment.yml
Change: use github.sha as default for commit in mattermost notify
We should us the same default as in the action.
None
> Change: use github.sha as default for commit in mattermost notify

- .github/workflows/test-python.yml
Remove caching of poetry for Python based CI workflows
Currently the caching seems to be broken since switching to pipx based installation of the applications. Therefore remove the caching of poetry for now.
https://github.com/greenbone/autohooks-plugin-pylint/actions/runs/5710696688/job/15514172248?pr=407
> Fix: Remove caching of poetry for Python based CI workflows

- .github/workflows/helm-build-push-3rd-gen.yml
- .github/workflows/notify-mattermost-3rd-gen.yml
Change: secrets in notify-mattermost-3rd-gen.yml
Dependabot don't have this secrets and on PR's this secrets are not needed.
None
> Change: secrets in notify-mattermost-3rd-gen.yml

- .github/workflows/notify-mattermost-qm.yml
- README.md
ADD: Workflow for Notify Mattermost QM
To have a clear separation between feed deployment and notifications for qm.
DOS-111
> ADD: Workflow for Notify Mattermost QM

- .github/workflows/helm-container-build-push-3rd-gen.yml
- README.md
Add: Option to set the greenbonebot token as image build arg in helm-container-build-push-3rd-gen.yml
Add: input option to enable notify
DEVOPS-821
DEVOPS-821
> Add: Option to set the greenbonebot token as image build arg

- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: use  GREENBONE_BOT_PACKAGES_READ_TOKEN in helm-container-build-push-3rd-gen.yml
Let's install the GREENBONE_BOT_PACKAGES_READ_TOKEN now so that the developers can rewrite their docker files
None
> Change: use  GREENBONE_BOT_PACKAGES_READ_TOKEN in helm-container-build-push-3rd-gen.yml

- .github/workflows/lint-python.yml
Fix wording for python linting workflow
It's possible to use a project specific linter and pylint isn't used always.
> Change: Fix wording for python linting workflow

- .github/workflows/release-cloud.yml
- .github/workflows/release-generic.yml
Extend workflow for cloud release process
Cloud will always create calendar based releases and tags without a
leading 'v'. Additionally the cloud workflow should not update the
version after a release to not create an additional commit.
All releases for the cloud will be marked as pre-releases initially and
are changed to "real" releases manually after testing the release.
DEVOPS-826
DEVOPS-828
> Extend release workflows

- .github/workflows/notify-mattermost-3rd-gen-ci.yml
- .github/workflows/notify-mattermost-3rd-gen.yml
- .github/workflows/notify-mattermost-feed-deployment.yml
- .github/workflows/notify-mattermost-qm.yml
Remove:  input validation from notify-mattermost-feed-deployment.yml
Github display of skipped jobs are horrible!! So remove this or nobody can see what's going on at first glance.
None
> Remove:  input validation from mattermost notify 

- .github/workflows/helm-build-push-postgres-3rd-gen.yml
Add: helm-build-push-postgres-3rd-gen.yml
I am seeking to establish a reusable workflow for releasing PostgreSQL Helm charts, as we have the requirement to release these types of charts from multiple repositories.
DEVOPS-848
> Add: helm-build-push-postgres-3rd-gen.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: Move trigger steps into own job in helm-container-build-push-3rd-gen.yml
DEVOPS-863
Much better to restart if the trigger steps fail.
DEVOPS-863
> Change: Move trigger steps into own job

- .github/workflows/helm-container-build-push-3rd-gen.yml
jobs
Change: split trigger service chart and trigger product chart into two
Through the division into two jobs, it is easy to restart only one job in case of an error, rather than allowing both to restart simultaneously.
None
> Change: split trigger service chart and trigger product chart into two

- .github/workflows/helm-container-build-push-3rd-gen.yml
- README.md
Change: ${{ github.repository }}" as image-url default in helm-container-build-push-3rd-gen.yml
It is mostly the default.
None
> Change: ${{ github.repository }}" as image-url default in helm-container-build-push-3rd-gen.yml

- .github/workflows/release-generic.yml
- .github/workflows/release-python.yml
Improve generic release workflows
Use more common code and make release workflows independent of the set default release type.
> Change: Improve generic release workflows

- .github/workflows/release-generic.yml
- .github/workflows/release-python.yml
Allow to use "calendar release" label for relase type calendar
Re-add "calendar release" label for creating calver releases. This label is used by the cloud team.
> Add: Allow to use "calendar release" label for relase type calendar

- .github/workflows/container-build-push-2nd-gen.yml
Add: Create multi arch manifest in container-build-push-2nd-gen.yml
We cannot use a matrix here because job outputs from matrix jobs cannot be passed to other jobs.
Due to cosign and the use of native runners, we cannot use the platform build mode from buildx anymore.
This means we have to build our own multi-arch manifest.
DEVOPS-1082
> Add: Create multi arch manifest in container-build-push-2nd-gen.yml

- .github/workflows/container-build-push-2nd-gen.yml
Change: Don't build arm images on PR's in container-build-push-2nd-gen.yml
At the moment we don't have enough arm runners to provide a run for every PR!
None
> Change: Don't build arm images on PR's in container-build-push-2nd-gen.yml

- .github/workflows/container-build-push-2nd-gen.yml
Change: Set github.ref_name as default for ref-name in container-build-push-2nd-gen.yml
We need always a ref name for is latest tag check.
DEVOPS-1135
> Change: Set github.ref_name as default for ref-name in container-build-push-2nd-gen.yml

- .github/workflows/container-build-push-2nd-gen.yml
Change: always set a tag-name on is-latest-tag action
It looks like the action doesn't use its default value even when an empty input is set.
None
> Change: always set a tag-name on is-latest-tag action

- .github/workflows/container-build-push-feed.yml
Special VTs case for unpacking artifact
The VTs artifact needs to be unpacked ...
DEVOPS-1138
> Add: Special VTs case for unpacking artifact

- .github/workflows/container-build-push-feed.yml
Change: notify to always in container-build-push-feed.yml
Some workflows chancel them self on an other job fail.
None
> Change: notify to always in container-build-push-feed.yml

- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: upload 3rd gen into greenbone registry
DEVOPS-1157
DEVOPS-1175
> Add: upload 3rd gen into greenbone registry

- .github/workflows/container-build-push-2nd-gen.yml
Add ~~image-type~~ base-image-label as input for container-build-push-2nd-gen workflow.
The ~~image-type~~ base-image-label is an enum with the following possible values:
- stable
- oldstable
- testing
According to the set value the image-tags are enabled.
We wanted to merge the container.yml and push.yml workflows in gvm-libs.
The legacy workflow builds additional gvm-libs containers with oldstable and testing tags.
To represent this logic we need to parametrize the container-build-push-2nd-gen workflow somehow.
https://jira.greenbone.net/browse/DEVOPS-1230
This is the PR requiring the changes: https://github.com/greenbone/gvm-libs/pull/838
https://github.com/greenbone/pipeline-experiments/actions/workflows/test-container-build-push-2nd-gen.yml
> Change: Add base-image-label as input, control image-tags by base-image-label.

- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: building-product-compose to notify in helm-container-build-push-3rd-gen.yml
Other wise the workflow will not be shown as failed in github.
None
> Add: building-product-compose to notify in helm-container-build-push-3rd-gen.yml

- .github/workflows/container-build-push-feed.yml
Notify job in cert-bund-data and scap-data is failing
startWith(github.ref ...) doesn't allow for anything other than version tags.
https://jira.greenbone.net/browse/DEVOPS-1225
> Fix: Fix by removing startWith(github.ref ...) condition

- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-feed.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
- .github/workflows/notify-mattermost-2nd-gen.yml
Change notification-channel for notify-mattermost-2nd-gen.yml
Adapt if conditions when using notify-mattermost* workflows
Currently https://github.com/greenbone/workflows/blob/main/.github/workflows/notify-mattermost-2nd-gen.yml#L36 notifies in channel: [PD:2ndGenDeployment](https://mattermost.greenbone.net/gb/channels/pd2ndgendeployment) but should be [TOD:FeedDeployment:Notification](https://mattermost.greenbone.net/gb/channels/pdfeeddeploymentnotification) 
Also check and adapt the if conditions for all workflows in greenbone/workflows using the notify-mattermost-2nd.gen workflow -> They should be run on every build.
https://jira.greenbone.net/browse/DEVOPS-1254
> Fix: Feed notification

- .github/workflows/helm-container-build-push-3rd-gen.yml
Add: missing building-container dep in helm-container-build-push-3rd-gen.yml
building-container job dependency is required to get the container digest for the compose upgrade.
None
> Add: missing building-container dep in helm-container-build-push-3rd-gen.yml

- .github/workflows/container-build-push-2nd-gen.yml
- .github/workflows/container-build-push-feed.yml
- .github/workflows/helm-container-build-push-3rd-gen.yml
Change: use vars.greenbone_registry not secrets.greenbone_registry
DEVOPS-1280
DEVOPS-1280
> Change: use vars.greenbone_registry not secrets.greenbone_registry

- .github/workflows/container-build-push-2nd-gen.yml
Add: product compose file udates from 2nd gen services
DEVOPS-1286
DEVOPS-1286
> Add: product compose file udates from 2nd gen services

- .github/workflows/container-build-push-2nd-gen.yml
Change: Allow edge tag on workflow_dispatch
Looks like the workflow https://github.com/greenbone/openvas-scanner/actions/runs/12252277373/job/34178550738 needs this.
None
> Change: Allow edge tag on workflow_dispatch

- .github/workflows/notify-mattermost-feed-deployment.yml
Updated feed update CI to use single line status notifications
Multi-Line notifications are using up a lot of space, and it is easier to see the current state and
recent trends if every status update just consists of a single line
> CI: Use short status notification

- .github/workflows/container-build-push-2nd-gen.yml
This adds GREENBONE_BOT_TOKEN as a workflow secret so that build pipelines that don't rely on inheritance are able to functions by providing it manually.
To fix: https://github.com/greenbone/openvas-scanner/actions/runs/12350274906/workflow
> Fix add GREENBONE_BOT_TOKEN as a secret when not able to inherit

- .github/workflows/container-build-push-3rd-gen.yml
Add UM to container build push
Because we want to build and push UM into registry
> Add: User-Management to container-build-push-3rd-gen.yml

- .github/workflows/container-build-push-2nd-gen.yml
Allow to override build-args for container build 2nd gen
The calling workflow should be able to specify the build-args. For example it should be possible to use whatever gvm-libs base image version the calling workflow needs and shouldn't limit to oldstable and oldstable-edge.
The change tries to be backwards compatible to still provide the old values if no build-args are passed.
https://jira.greenbone.net/browse/GEA-791
> Allow to override build-args for container build 2nd gen

- .github/workflows/lint-python.yml
Allow to specify a format checking tool for python linting workflow
Besides black there is ruff format, which is much faster.
Requires https://github.com/greenbone/actions/pull/1325
>  Allow to specify a format checking tool for python linting workflow

- .github/workflows/notify-mattermost-2nd-gen.yml
- .github/workflows/notify-mattermost-3rd-gen-ci.yml
- .github/workflows/notify-mattermost-3rd-gen.yml
- .github/workflows/notify-mattermost-feed-deployment.yml
- .github/workflows/notify-mattermost-qm.yml
Add: shortline support for notify mattermost workflows
With this change we can disable/enable default is enable the shortline mode in every workflow.
For example here it is already used, but this input option never existed. https://github.com/greenbone/greenbone-docker/actions/runs/13362015979/workflow#L146 
None
> Add: shortline support for notify mattermost workflows

- .github/workflows/generate-and-push-sbom-with-trivy-3rd-gen.yml
- README.md
- Add a workflow that generates an SBOM with trivy, cosgins the output file and pushes it to a specified registry
To add the container image SBOMs of the new products to the registry, so that it can be delivered to customers.
Currently this workflow only supports trivy's image scanning.
T5-1437
- [n/a] Tests
> Add: Add a workflow to generate an SBOM with trivy

- .github/workflows/gh-pages-helper.sh
- .github/workflows/gh-pages.yml
- Add step to clean local directories, so always latest downloaded artifacts are considered.
- Add PR number, GIT ref name, run id in root html so that the reviewers knows if the file is not override by another run
To make it easier for reviewer
https://jira.greenbone.net/browse/DEVOPS-1677
github pages: https://github.com/greenbone/workflows/pull/188
> Add: Clean local dir & add Ref name, PR number to github-pages

- .github/workflows/container-build-push-gea.yml
Allow to disable container tags for pr based builds
Also only create multi-arch images if we have tags.
> Allow to disable container tags for pr based builds

- .github/workflows/container-build-push-3rd-gen.yml
Add unstable-release tags for release branch image builds.
This is needed to have a tag available after a merge to a release branch from a hotfix branch. Currently the workflow fails, because it can not determine a proper flag.
DOS-421
T5-1642
> Add(3rdgen): unstable-release tags for release branch image builds

- .github/workflows/container-build-push-3rd-gen.yml
Using release branch names like `release/vX.X.X` is more natural to github than `release-vX.X.X`.
DOS-421
> Change(3rdgen): Update release branch filter for unstable tag
